export const ROUTES = {
  home: '/',
  features: '/features',
  pricing: '/pricing',
  about: '/about',
  faq: '/faq',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',

  app: '/app',
  journal: '/app/journal',
  calendar: '/app/calendar',
  analytics: '/app/analytics',
  risk: '/app/risk',
  strategies: '/app/strategies',
  psychology: '/app/psychology',
  fame: '/app/hall-of-fame',
  shame: '/app/hall-of-shame',
  reports: '/app/reports',
  settings: '/app/settings',
  membership: '/app/membership',

  admin: '/admin',
  adminUsers: '/admin/users',
  adminSubscriptions: '/admin/subscriptions',
  adminPlans: '/admin/plans',
  adminInstruments: '/admin/instruments',
  adminFeedback: '/admin/feedback',
  adminAudit: '/admin/audit',

  terms: '/terms',
  privacy: '/privacy',
  refunds: '/refunds',
  contact: '/contact',
} as const;
