-- =============================================================================
-- Phase 2 · INSTRUMENT UNIVERSE
-- =============================================================================
-- GENERATED FILE — do not edit by hand.
-- Source: src/constants/data/forexPairs.json + indianInstruments.json
-- Regenerate: npm run gen:instruments
--
-- Replaces the Phase 1 starter seed with the full universe:
--   • 78 forex/CFD symbols with REAL contract specs. Metals and crypto are
--     no longer treated as 100,000-unit currency pairs — gold is 100 oz with a
--     0.01 pip, which previously overstated gold P&L by ~1000x.
--   • 8 indices and 468 NSE/BSE names as a UNION: one row per company,
--     with other listings in also_on, so RELIANCE appears once rather than
--     twice. has_fno marks the 213 names with a derivatives contract;
--     those trade as EQ/FUT/OPT, the rest are cash-only (lot_size 1, where
--     quantity means SHARES).
--
-- LOT SIZES: revised by the exchanges several times a year. These reflect
-- 2025-01 and MUST be re-verified against the current circular before launch.
-- They are admin-editable and overridable per trade, so a stale value here can
-- never silently corrupt a user's P&L.
-- =============================================================================

begin;

alter table public.instruments add column if not exists has_fno boolean not null default false;

-- 'index' | 'fno' | 'cash' join the forex categories.
alter table public.instruments drop constraint if exists instruments_category_check;

insert into public.instruments
  (id, trading_mode, symbol, name, exchange, also_on, segment, has_fno,
   base_currency, quote_currency, contract_size, lot_size, pip_size, tick_size,
   category, sort_order)
values
  ('FX:EURUSD', 'forex', 'EUR/USD', 'EUR / USD', null, '{}'::text[], null, false, 'EUR', 'USD', 100000, 100000, 0.0001, 0.00001, 'major', 10),
  ('FX:GBPUSD', 'forex', 'GBP/USD', 'GBP / USD', null, '{}'::text[], null, false, 'GBP', 'USD', 100000, 100000, 0.0001, 0.00001, 'major', 20),
  ('FX:USDJPY', 'forex', 'USD/JPY', 'USD / JPY', null, '{}'::text[], null, false, 'USD', 'JPY', 100000, 100000, 0.01, 0.001, 'major', 30),
  ('FX:USDCHF', 'forex', 'USD/CHF', 'USD / CHF', null, '{}'::text[], null, false, 'USD', 'CHF', 100000, 100000, 0.0001, 0.00001, 'major', 40),
  ('FX:AUDUSD', 'forex', 'AUD/USD', 'AUD / USD', null, '{}'::text[], null, false, 'AUD', 'USD', 100000, 100000, 0.0001, 0.00001, 'major', 50),
  ('FX:USDCAD', 'forex', 'USD/CAD', 'USD / CAD', null, '{}'::text[], null, false, 'USD', 'CAD', 100000, 100000, 0.0001, 0.00001, 'major', 60),
  ('FX:NZDUSD', 'forex', 'NZD/USD', 'NZD / USD', null, '{}'::text[], null, false, 'NZD', 'USD', 100000, 100000, 0.0001, 0.00001, 'major', 70),
  ('FX:EURGBP', 'forex', 'EUR/GBP', 'EUR / GBP', null, '{}'::text[], null, false, 'EUR', 'GBP', 100000, 100000, 0.0001, 0.00001, 'minor', 80),
  ('FX:EURJPY', 'forex', 'EUR/JPY', 'EUR / JPY', null, '{}'::text[], null, false, 'EUR', 'JPY', 100000, 100000, 0.01, 0.001, 'minor', 90),
  ('FX:EURCHF', 'forex', 'EUR/CHF', 'EUR / CHF', null, '{}'::text[], null, false, 'EUR', 'CHF', 100000, 100000, 0.0001, 0.00001, 'minor', 100),
  ('FX:EURAUD', 'forex', 'EUR/AUD', 'EUR / AUD', null, '{}'::text[], null, false, 'EUR', 'AUD', 100000, 100000, 0.0001, 0.00001, 'minor', 110),
  ('FX:EURCAD', 'forex', 'EUR/CAD', 'EUR / CAD', null, '{}'::text[], null, false, 'EUR', 'CAD', 100000, 100000, 0.0001, 0.00001, 'minor', 120),
  ('FX:EURNZD', 'forex', 'EUR/NZD', 'EUR / NZD', null, '{}'::text[], null, false, 'EUR', 'NZD', 100000, 100000, 0.0001, 0.00001, 'minor', 130),
  ('FX:GBPJPY', 'forex', 'GBP/JPY', 'GBP / JPY', null, '{}'::text[], null, false, 'GBP', 'JPY', 100000, 100000, 0.01, 0.001, 'minor', 140),
  ('FX:GBPCHF', 'forex', 'GBP/CHF', 'GBP / CHF', null, '{}'::text[], null, false, 'GBP', 'CHF', 100000, 100000, 0.0001, 0.00001, 'minor', 150),
  ('FX:GBPAUD', 'forex', 'GBP/AUD', 'GBP / AUD', null, '{}'::text[], null, false, 'GBP', 'AUD', 100000, 100000, 0.0001, 0.00001, 'minor', 160),
  ('FX:GBPCAD', 'forex', 'GBP/CAD', 'GBP / CAD', null, '{}'::text[], null, false, 'GBP', 'CAD', 100000, 100000, 0.0001, 0.00001, 'minor', 170),
  ('FX:GBPNZD', 'forex', 'GBP/NZD', 'GBP / NZD', null, '{}'::text[], null, false, 'GBP', 'NZD', 100000, 100000, 0.0001, 0.00001, 'minor', 180),
  ('FX:AUDJPY', 'forex', 'AUD/JPY', 'AUD / JPY', null, '{}'::text[], null, false, 'AUD', 'JPY', 100000, 100000, 0.01, 0.001, 'minor', 190),
  ('FX:AUDCHF', 'forex', 'AUD/CHF', 'AUD / CHF', null, '{}'::text[], null, false, 'AUD', 'CHF', 100000, 100000, 0.0001, 0.00001, 'minor', 200),
  ('FX:AUDCAD', 'forex', 'AUD/CAD', 'AUD / CAD', null, '{}'::text[], null, false, 'AUD', 'CAD', 100000, 100000, 0.0001, 0.00001, 'minor', 210),
  ('FX:AUDNZD', 'forex', 'AUD/NZD', 'AUD / NZD', null, '{}'::text[], null, false, 'AUD', 'NZD', 100000, 100000, 0.0001, 0.00001, 'minor', 220),
  ('FX:NZDJPY', 'forex', 'NZD/JPY', 'NZD / JPY', null, '{}'::text[], null, false, 'NZD', 'JPY', 100000, 100000, 0.01, 0.001, 'minor', 230),
  ('FX:NZDCHF', 'forex', 'NZD/CHF', 'NZD / CHF', null, '{}'::text[], null, false, 'NZD', 'CHF', 100000, 100000, 0.0001, 0.00001, 'minor', 240),
  ('FX:NZDCAD', 'forex', 'NZD/CAD', 'NZD / CAD', null, '{}'::text[], null, false, 'NZD', 'CAD', 100000, 100000, 0.0001, 0.00001, 'minor', 250),
  ('FX:CADJPY', 'forex', 'CAD/JPY', 'CAD / JPY', null, '{}'::text[], null, false, 'CAD', 'JPY', 100000, 100000, 0.01, 0.001, 'minor', 260),
  ('FX:CADCHF', 'forex', 'CAD/CHF', 'CAD / CHF', null, '{}'::text[], null, false, 'CAD', 'CHF', 100000, 100000, 0.0001, 0.00001, 'minor', 270),
  ('FX:CHFJPY', 'forex', 'CHF/JPY', 'CHF / JPY', null, '{}'::text[], null, false, 'CHF', 'JPY', 100000, 100000, 0.01, 0.001, 'minor', 280),
  ('FX:USDINR', 'forex', 'USD/INR', 'USD / INR', null, '{}'::text[], null, false, 'USD', 'INR', 100000, 100000, 0.0001, 0.00001, 'exotic', 290),
  ('FX:EURINR', 'forex', 'EUR/INR', 'EUR / INR', null, '{}'::text[], null, false, 'EUR', 'INR', 100000, 100000, 0.0001, 0.00001, 'exotic', 300),
  ('FX:GBPINR', 'forex', 'GBP/INR', 'GBP / INR', null, '{}'::text[], null, false, 'GBP', 'INR', 100000, 100000, 0.0001, 0.00001, 'exotic', 310),
  ('FX:JPYINR', 'forex', 'JPY/INR', 'JPY / INR', null, '{}'::text[], null, false, 'JPY', 'INR', 100000, 100000, 0.0001, 0.00001, 'exotic', 320),
  ('FX:USDSGD', 'forex', 'USD/SGD', 'USD / SGD', null, '{}'::text[], null, false, 'USD', 'SGD', 100000, 100000, 0.0001, 0.00001, 'exotic', 330),
  ('FX:USDHKD', 'forex', 'USD/HKD', 'USD / HKD', null, '{}'::text[], null, false, 'USD', 'HKD', 100000, 100000, 0.0001, 0.00001, 'exotic', 340),
  ('FX:USDCNH', 'forex', 'USD/CNH', 'USD / CNH', null, '{}'::text[], null, false, 'USD', 'CNH', 100000, 100000, 0.0001, 0.00001, 'exotic', 350),
  ('FX:USDZAR', 'forex', 'USD/ZAR', 'USD / ZAR', null, '{}'::text[], null, false, 'USD', 'ZAR', 100000, 100000, 0.0001, 0.00001, 'exotic', 360),
  ('FX:USDMXN', 'forex', 'USD/MXN', 'USD / MXN', null, '{}'::text[], null, false, 'USD', 'MXN', 100000, 100000, 0.0001, 0.00001, 'exotic', 370),
  ('FX:USDTRY', 'forex', 'USD/TRY', 'USD / TRY', null, '{}'::text[], null, false, 'USD', 'TRY', 100000, 100000, 0.0001, 0.00001, 'exotic', 380),
  ('FX:USDNOK', 'forex', 'USD/NOK', 'USD / NOK', null, '{}'::text[], null, false, 'USD', 'NOK', 100000, 100000, 0.0001, 0.00001, 'exotic', 390),
  ('FX:USDSEK', 'forex', 'USD/SEK', 'USD / SEK', null, '{}'::text[], null, false, 'USD', 'SEK', 100000, 100000, 0.0001, 0.00001, 'exotic', 400),
  ('FX:USDDKK', 'forex', 'USD/DKK', 'USD / DKK', null, '{}'::text[], null, false, 'USD', 'DKK', 100000, 100000, 0.0001, 0.00001, 'exotic', 410),
  ('FX:USDPLN', 'forex', 'USD/PLN', 'USD / PLN', null, '{}'::text[], null, false, 'USD', 'PLN', 100000, 100000, 0.0001, 0.00001, 'exotic', 420),
  ('FX:USDCZK', 'forex', 'USD/CZK', 'USD / CZK', null, '{}'::text[], null, false, 'USD', 'CZK', 100000, 100000, 0.0001, 0.00001, 'exotic', 430),
  ('FX:USDHUF', 'forex', 'USD/HUF', 'USD / HUF', null, '{}'::text[], null, false, 'USD', 'HUF', 100000, 100000, 0.01, 0.001, 'exotic', 440),
  ('FX:USDTHB', 'forex', 'USD/THB', 'USD / THB', null, '{}'::text[], null, false, 'USD', 'THB', 100000, 100000, 0.0001, 0.00001, 'exotic', 450),
  ('FX:USDAED', 'forex', 'USD/AED', 'USD / AED', null, '{}'::text[], null, false, 'USD', 'AED', 100000, 100000, 0.0001, 0.00001, 'exotic', 460),
  ('FX:USDSAR', 'forex', 'USD/SAR', 'USD / SAR', null, '{}'::text[], null, false, 'USD', 'SAR', 100000, 100000, 0.0001, 0.00001, 'exotic', 470),
  ('FX:USDILS', 'forex', 'USD/ILS', 'USD / ILS', null, '{}'::text[], null, false, 'USD', 'ILS', 100000, 100000, 0.0001, 0.00001, 'exotic', 480),
  ('FX:USDBRL', 'forex', 'USD/BRL', 'USD / BRL', null, '{}'::text[], null, false, 'USD', 'BRL', 100000, 100000, 0.0001, 0.00001, 'exotic', 490),
  ('FX:USDPHP', 'forex', 'USD/PHP', 'USD / PHP', null, '{}'::text[], null, false, 'USD', 'PHP', 100000, 100000, 0.0001, 0.00001, 'exotic', 500),
  ('FX:USDTWD', 'forex', 'USD/TWD', 'USD / TWD', null, '{}'::text[], null, false, 'USD', 'TWD', 100000, 100000, 0.0001, 0.00001, 'exotic', 510),
  ('FX:USDKRW', 'forex', 'USD/KRW', 'USD / KRW', null, '{}'::text[], null, false, 'USD', 'KRW', 100000, 100000, 0.01, 0.001, 'exotic', 520),
  ('FX:EURTRY', 'forex', 'EUR/TRY', 'EUR / TRY', null, '{}'::text[], null, false, 'EUR', 'TRY', 100000, 100000, 0.0001, 0.00001, 'exotic', 530),
  ('FX:EURZAR', 'forex', 'EUR/ZAR', 'EUR / ZAR', null, '{}'::text[], null, false, 'EUR', 'ZAR', 100000, 100000, 0.0001, 0.00001, 'exotic', 540),
  ('FX:EURMXN', 'forex', 'EUR/MXN', 'EUR / MXN', null, '{}'::text[], null, false, 'EUR', 'MXN', 100000, 100000, 0.0001, 0.00001, 'exotic', 550),
  ('FX:EURNOK', 'forex', 'EUR/NOK', 'EUR / NOK', null, '{}'::text[], null, false, 'EUR', 'NOK', 100000, 100000, 0.0001, 0.00001, 'exotic', 560),
  ('FX:EURSEK', 'forex', 'EUR/SEK', 'EUR / SEK', null, '{}'::text[], null, false, 'EUR', 'SEK', 100000, 100000, 0.0001, 0.00001, 'exotic', 570),
  ('FX:EURPLN', 'forex', 'EUR/PLN', 'EUR / PLN', null, '{}'::text[], null, false, 'EUR', 'PLN', 100000, 100000, 0.0001, 0.00001, 'exotic', 580),
  ('FX:EURHUF', 'forex', 'EUR/HUF', 'EUR / HUF', null, '{}'::text[], null, false, 'EUR', 'HUF', 100000, 100000, 0.01, 0.001, 'exotic', 590),
  ('FX:EURCZK', 'forex', 'EUR/CZK', 'EUR / CZK', null, '{}'::text[], null, false, 'EUR', 'CZK', 100000, 100000, 0.0001, 0.00001, 'exotic', 600),
  ('FX:EURSGD', 'forex', 'EUR/SGD', 'EUR / SGD', null, '{}'::text[], null, false, 'EUR', 'SGD', 100000, 100000, 0.0001, 0.00001, 'exotic', 610),
  ('FX:GBPZAR', 'forex', 'GBP/ZAR', 'GBP / ZAR', null, '{}'::text[], null, false, 'GBP', 'ZAR', 100000, 100000, 0.0001, 0.00001, 'exotic', 620),
  ('FX:GBPSGD', 'forex', 'GBP/SGD', 'GBP / SGD', null, '{}'::text[], null, false, 'GBP', 'SGD', 100000, 100000, 0.0001, 0.00001, 'exotic', 630),
  ('FX:AUDSGD', 'forex', 'AUD/SGD', 'AUD / SGD', null, '{}'::text[], null, false, 'AUD', 'SGD', 100000, 100000, 0.0001, 0.00001, 'exotic', 640),
  ('FX:SGDJPY', 'forex', 'SGD/JPY', 'SGD / JPY', null, '{}'::text[], null, false, 'SGD', 'JPY', 100000, 100000, 0.01, 0.001, 'exotic', 650),
  ('FX:ZARJPY', 'forex', 'ZAR/JPY', 'ZAR / JPY', null, '{}'::text[], null, false, 'ZAR', 'JPY', 100000, 100000, 0.01, 0.001, 'exotic', 660),
  ('FX:TRYJPY', 'forex', 'TRY/JPY', 'TRY / JPY', null, '{}'::text[], null, false, 'TRY', 'JPY', 100000, 100000, 0.01, 0.001, 'exotic', 670),
  ('FX:NOKSEK', 'forex', 'NOK/SEK', 'NOK / SEK', null, '{}'::text[], null, false, 'NOK', 'SEK', 100000, 100000, 0.0001, 0.00001, 'exotic', 680),
  ('FX:XAUUSD', 'forex', 'XAU/USD', 'Gold / US Dollar', null, '{}'::text[], null, false, 'XAU', 'USD', 100, 100, 0.01, 0.01, 'metal', 690),
  ('FX:XAGUSD', 'forex', 'XAG/USD', 'Silver / US Dollar', null, '{}'::text[], null, false, 'XAG', 'USD', 5000, 5000, 0.001, 0.001, 'metal', 700),
  ('FX:XPTUSD', 'forex', 'XPT/USD', 'Platinum / US Dollar', null, '{}'::text[], null, false, 'XPT', 'USD', 50, 50, 0.01, 0.01, 'metal', 710),
  ('FX:XPDUSD', 'forex', 'XPD/USD', 'Palladium / US Dollar', null, '{}'::text[], null, false, 'XPD', 'USD', 100, 100, 0.01, 0.01, 'metal', 720),
  ('FX:XAUEUR', 'forex', 'XAU/EUR', 'Gold / Euro', null, '{}'::text[], null, false, 'XAU', 'EUR', 100, 100, 0.01, 0.01, 'metal', 730),
  ('FX:BTCUSD', 'forex', 'BTC/USD', 'Bitcoin / US Dollar', null, '{}'::text[], null, false, 'BTC', 'USD', 1, 1, 0.01, 0.01, 'crypto', 740),
  ('FX:ETHUSD', 'forex', 'ETH/USD', 'Ethereum / US Dollar', null, '{}'::text[], null, false, 'ETH', 'USD', 1, 1, 0.01, 0.01, 'crypto', 750),
  ('FX:XRPUSD', 'forex', 'XRP/USD', 'Ripple / US Dollar', null, '{}'::text[], null, false, 'XRP', 'USD', 1, 1, 0.0001, 0.0001, 'crypto', 760),
  ('FX:SOLUSD', 'forex', 'SOL/USD', 'Solana / US Dollar', null, '{}'::text[], null, false, 'SOL', 'USD', 1, 1, 0.01, 0.01, 'crypto', 770),
  ('FX:LTCUSD', 'forex', 'LTC/USD', 'Litecoin / US Dollar', null, '{}'::text[], null, false, 'LTC', 'USD', 1, 1, 0.01, 0.01, 'crypto', 780),
  ('NSE:NIFTY', 'indian', 'NIFTY', 'Nifty 50', 'NSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 75, null, 0.05, 'index', 10),
  ('NSE:BANKNIFTY', 'indian', 'BANKNIFTY', 'Nifty Bank', 'NSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 30, null, 0.05, 'index', 20),
  ('NSE:FINNIFTY', 'indian', 'FINNIFTY', 'Nifty Financial Services', 'NSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 65, null, 0.05, 'index', 30),
  ('NSE:MIDCPNIFTY', 'indian', 'MIDCPNIFTY', 'Nifty Midcap Select', 'NSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 120, null, 0.05, 'index', 40),
  ('NSE:NIFTYNXT50', 'indian', 'NIFTYNXT50', 'Nifty Next 50', 'NSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 25, null, 0.05, 'index', 50),
  ('BSE:SENSEX', 'indian', 'SENSEX', 'BSE Sensex', 'BSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 20, null, 0.05, 'index', 60),
  ('BSE:BANKEX', 'indian', 'BANKEX', 'BSE Bankex', 'BSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 30, null, 0.05, 'index', 70),
  ('BSE:SENSEX50', 'indian', 'SENSEX50', 'BSE Sensex 50', 'BSE', '{}'::text[], 'INDEX', true, null, 'INR', 1, 60, null, 0.05, 'index', 80),
  ('NSE:360ONE', 'indian', '360ONE', '360 ONE WAM', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1010),
  ('NSE:3MINDIA', 'indian', '3MINDIA', '3M India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1020),
  ('NSE:AARTIIND', 'indian', 'AARTIIND', 'Aarti Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1450, null, 0.05, 'fno', 1030),
  ('NSE:ABB', 'indian', 'ABB', 'ABB India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 125, null, 0.05, 'fno', 1040),
  ('NSE:ABBOTINDIA', 'indian', 'ABBOTINDIA', 'Abbott India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 25, null, 0.05, 'fno', 1050),
  ('NSE:ABCAPITAL', 'indian', 'ABCAPITAL', 'Aditya Birla Capital', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3100, null, 0.05, 'fno', 1060),
  ('NSE:ABFRL', 'indian', 'ABFRL', 'Aditya Birla Fashion & Retail', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2600, null, 0.05, 'fno', 1070),
  ('NSE:ABSLAMC', 'indian', 'ABSLAMC', 'Aditya Birla Sun Life AMC', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1080),
  ('NSE:ACC', 'indian', 'ACC', 'ACC', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 300, null, 0.05, 'fno', 1090),
  ('NSE:ADANIENSOL', 'indian', 'ADANIENSOL', 'Adani Energy Solutions', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 675, null, 0.05, 'fno', 1100),
  ('NSE:ADANIENT', 'indian', 'ADANIENT', 'Adani Enterprises', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 300, null, 0.05, 'fno', 1110),
  ('NSE:ADANIGREEN', 'indian', 'ADANIGREEN', 'Adani Green Energy', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 600, null, 0.05, 'fno', 1120),
  ('NSE:ADANIPORTS', 'indian', 'ADANIPORTS', 'Adani Ports & SEZ', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 475, null, 0.05, 'fno', 1130),
  ('NSE:ADANIPOWER', 'indian', 'ADANIPOWER', 'Adani Power', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1140),
  ('NSE:AEGISLOG', 'indian', 'AEGISLOG', 'Aegis Logistics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1150),
  ('NSE:AFFLE', 'indian', 'AFFLE', 'Affle India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1160),
  ('NSE:AHLUCONT', 'indian', 'AHLUCONT', 'Ahluwalia Contracts India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1170),
  ('NSE:AIAENG', 'indian', 'AIAENG', 'AIA Engineering', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1180),
  ('NSE:AJANTPHARM', 'indian', 'AJANTPHARM', 'Ajanta Pharma', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1190),
  ('NSE:AKZOINDIA', 'indian', 'AKZOINDIA', 'Akzo Nobel India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1200),
  ('NSE:ALKEM', 'indian', 'ALKEM', 'Alkem Laboratories', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 125, null, 0.05, 'fno', 1210),
  ('NSE:ALKYLAMINE', 'indian', 'ALKYLAMINE', 'Alkyl Amines Chemicals', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1220),
  ('NSE:ALLCARGO', 'indian', 'ALLCARGO', 'Allcargo Logistics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1230),
  ('NSE:AMBER', 'indian', 'AMBER', 'Amber Enterprises India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1240),
  ('NSE:AMBUJACEM', 'indian', 'AMBUJACEM', 'Ambuja Cements', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1050, null, 0.05, 'fno', 1250),
  ('NSE:ANANDRATHI', 'indian', 'ANANDRATHI', 'Anand Rathi Wealth', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1260),
  ('NSE:ANANTRAJ', 'indian', 'ANANTRAJ', 'Anant Raj', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1270),
  ('NSE:ANGELONE', 'indian', 'ANGELONE', 'Angel One', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 250, null, 0.05, 'fno', 1280),
  ('NSE:APARINDS', 'indian', 'APARINDS', 'Apar Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1290),
  ('NSE:APLAPOLLO', 'indian', 'APLAPOLLO', 'APL Apollo Tubes', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 1300),
  ('NSE:APOLLOHOSP', 'indian', 'APOLLOHOSP', 'Apollo Hospitals Enterprise', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 125, null, 0.05, 'fno', 1310),
  ('NSE:APOLLOTYRE', 'indian', 'APOLLOTYRE', 'Apollo Tyres', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1700, null, 0.05, 'fno', 1320),
  ('NSE:ARVIND', 'indian', 'ARVIND', 'Arvind', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1330),
  ('NSE:ASHOKLEY', 'indian', 'ASHOKLEY', 'Ashok Leyland', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 5000, null, 0.05, 'fno', 1340),
  ('NSE:ASIANPAINT', 'indian', 'ASIANPAINT', 'Asian Paints', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 1350),
  ('NSE:ASTERDM', 'indian', 'ASTERDM', 'Aster DM Healthcare', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1360),
  ('NSE:ASTRAL', 'indian', 'ASTRAL', 'Astral', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 425, null, 0.05, 'fno', 1370),
  ('NSE:ASTRAMICRO', 'indian', 'ASTRAMICRO', 'Astra Microwave Products', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1380),
  ('NSE:ATGL', 'indian', 'ATGL', 'Adani Total Gas', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1390),
  ('NSE:ATUL', 'indian', 'ATUL', 'Atul', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 75, null, 0.05, 'fno', 1400),
  ('NSE:AUBANK', 'indian', 'AUBANK', 'AU Small Finance Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 1410),
  ('NSE:AUROPHARMA', 'indian', 'AUROPHARMA', 'Aurobindo Pharma', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 550, null, 0.05, 'fno', 1420),
  ('NSE:AVALON', 'indian', 'AVALON', 'Avalon Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1430),
  ('NSE:AVANTIFEED', 'indian', 'AVANTIFEED', 'Avanti Feeds', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1440),
  ('NSE:AWL', 'indian', 'AWL', 'AWL Agri Business', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1450),
  ('NSE:AXISBANK', 'indian', 'AXISBANK', 'Axis Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 625, null, 0.05, 'fno', 1460),
  ('NSE:AZAD', 'indian', 'AZAD', 'Azad Engineering', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1470),
  ('NSE:BAJAJ-AUTO', 'indian', 'BAJAJ-AUTO', 'Bajaj Auto', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 75, null, 0.05, 'fno', 1480),
  ('NSE:BAJAJFINSV', 'indian', 'BAJAJFINSV', 'Bajaj Finserv', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 500, null, 0.05, 'fno', 1490),
  ('NSE:BAJAJHLDNG', 'indian', 'BAJAJHLDNG', 'Bajaj Holdings & Investment', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1500),
  ('NSE:BAJFINANCE', 'indian', 'BAJFINANCE', 'Bajaj Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 750, null, 0.05, 'fno', 1510),
  ('NSE:BALAMINES', 'indian', 'BALAMINES', 'Balaji Amines', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1520),
  ('NSE:BALKRISIND', 'indian', 'BALKRISIND', 'Balkrishna Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 300, null, 0.05, 'fno', 1530),
  ('NSE:BALRAMCHIN', 'indian', 'BALRAMCHIN', 'Balrampur Chini Mills', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1540),
  ('NSE:BANDHANBNK', 'indian', 'BANDHANBNK', 'Bandhan Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3600, null, 0.05, 'fno', 1550),
  ('NSE:BANKBARODA', 'indian', 'BANKBARODA', 'Bank of Baroda', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2925, null, 0.05, 'fno', 1560),
  ('NSE:BARBEQUE', 'indian', 'BARBEQUE', 'Barbeque Nation Hospitality', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1570),
  ('NSE:BATAINDIA', 'indian', 'BATAINDIA', 'Bata India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1580),
  ('NSE:BAYERCROP', 'indian', 'BAYERCROP', 'Bayer CropScience', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1590),
  ('NSE:BDL', 'indian', 'BDL', 'Bharat Dynamics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1600),
  ('NSE:BEL', 'indian', 'BEL', 'Bharat Electronics', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2850, null, 0.05, 'fno', 1610),
  ('NSE:BEML', 'indian', 'BEML', 'BEML', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1620),
  ('NSE:BERGEPAINT', 'indian', 'BERGEPAINT', 'Berger Paints India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1100, null, 0.05, 'fno', 1630),
  ('NSE:BHARATFORG', 'indian', 'BHARATFORG', 'Bharat Forge', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 500, null, 0.05, 'fno', 1640),
  ('NSE:BHARTIARTL', 'indian', 'BHARTIARTL', 'Bharti Airtel', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 475, null, 0.05, 'fno', 1650),
  ('NSE:BHEL', 'indian', 'BHEL', 'Bharat Heavy Electricals', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2625, null, 0.05, 'fno', 1660),
  ('NSE:BIKAJI', 'indian', 'BIKAJI', 'Bikaji Foods International', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1670),
  ('NSE:BIOCON', 'indian', 'BIOCON', 'Biocon', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2500, null, 0.05, 'fno', 1680),
  ('NSE:BLISSGVS', 'indian', 'BLISSGVS', 'Bliss GVS Pharma', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1690),
  ('NSE:BLUEDART', 'indian', 'BLUEDART', 'Blue Dart Express', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1700),
  ('NSE:BLUESTARCO', 'indian', 'BLUESTARCO', 'Blue Star', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1710),
  ('NSE:BORORENEW', 'indian', 'BORORENEW', 'Borosil Renewables', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1720),
  ('NSE:BOSCHLTD', 'indian', 'BOSCHLTD', 'Bosch', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 25, null, 0.05, 'fno', 1730),
  ('NSE:BPCL', 'indian', 'BPCL', 'Bharat Petroleum Corporation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1975, null, 0.05, 'fno', 1740),
  ('NSE:BRIGADE', 'indian', 'BRIGADE', 'Brigade Enterprises', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1750),
  ('NSE:BRITANNIA', 'indian', 'BRITANNIA', 'Britannia Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 1760),
  ('NSE:BSE', 'indian', 'BSE', 'BSE', 'NSE', '{}'::text[], 'EQ', true, null, 'INR', 1, 375, null, 0.05, 'fno', 1770),
  ('NSE:BSOFT', 'indian', 'BSOFT', 'Birlasoft', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1250, null, 0.05, 'fno', 1780),
  ('NSE:CAMLINFINE', 'indian', 'CAMLINFINE', 'Camlin Fine Sciences', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1790),
  ('NSE:CAMS', 'indian', 'CAMS', 'Computer Age Management Services', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1800),
  ('NSE:CANBK', 'indian', 'CANBK', 'Canara Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 6750, null, 0.05, 'fno', 1810),
  ('NSE:CAPLIPOINT', 'indian', 'CAPLIPOINT', 'Caplin Point Laboratories', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1820),
  ('NSE:CARBORUNIV', 'indian', 'CARBORUNIV', 'Carborundum Universal', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1830),
  ('NSE:CASTROLIND', 'indian', 'CASTROLIND', 'Castrol India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1840),
  ('NSE:CCL', 'indian', 'CCL', 'CCL Products India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1850),
  ('NSE:CDSL', 'indian', 'CDSL', 'Central Depository Services India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 475, null, 0.05, 'fno', 1860),
  ('NSE:CENTRALBK', 'indian', 'CENTRALBK', 'Central Bank of India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1870),
  ('NSE:CENTURYPLY', 'indian', 'CENTURYPLY', 'Century Plyboards India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1880),
  ('NSE:CERA', 'indian', 'CERA', 'Cera Sanitaryware', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1890),
  ('NSE:CGPOWER', 'indian', 'CGPOWER', 'CG Power & Industrial Solutions', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 850, null, 0.05, 'fno', 1900),
  ('NSE:CHALET', 'indian', 'CHALET', 'Chalet Hotels', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1910),
  ('NSE:CHAMBLFERT', 'indian', 'CHAMBLFERT', 'Chambal Fertilisers & Chemicals', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1100, null, 0.05, 'fno', 1920),
  ('NSE:CHOLAFIN', 'indian', 'CHOLAFIN', 'Cholamandalam Investment & Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 625, null, 0.05, 'fno', 1930),
  ('NSE:CIPLA', 'indian', 'CIPLA', 'Cipla', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 650, null, 0.05, 'fno', 1940),
  ('NSE:CLEAN', 'indian', 'CLEAN', 'Clean Science & Technology', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1950),
  ('NSE:COALINDIA', 'indian', 'COALINDIA', 'Coal India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1350, null, 0.05, 'fno', 1960),
  ('NSE:COCHINSHIP', 'indian', 'COCHINSHIP', 'Cochin Shipyard', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 1970),
  ('NSE:COFORGE', 'indian', 'COFORGE', 'Coforge', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 1980),
  ('NSE:COLPAL', 'indian', 'COLPAL', 'Colgate-Palmolive India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 1990),
  ('NSE:CONCOR', 'indian', 'CONCOR', 'Container Corporation of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 2000),
  ('NSE:COROMANDEL', 'indian', 'COROMANDEL', 'Coromandel International', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 2010),
  ('NSE:CREDITACC', 'indian', 'CREDITACC', 'CreditAccess Grameen', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2020),
  ('NSE:CROMPTON', 'indian', 'CROMPTON', 'Crompton Greaves Consumer Electricals', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1800, null, 0.05, 'fno', 2030),
  ('NSE:CUB', 'indian', 'CUB', 'City Union Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2040),
  ('NSE:CUMMINSIND', 'indian', 'CUMMINSIND', 'Cummins India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 2050),
  ('NSE:CYIENT', 'indian', 'CYIENT', 'Cyient', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 425, null, 0.05, 'fno', 2060),
  ('NSE:DABUR', 'indian', 'DABUR', 'Dabur India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1250, null, 0.05, 'fno', 2070),
  ('NSE:DALBHARAT', 'indian', 'DALBHARAT', 'Dalmia Bharat', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 325, null, 0.05, 'fno', 2080),
  ('NSE:DATAPATTNS', 'indian', 'DATAPATTNS', 'Data Patterns India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2090),
  ('NSE:DCBBANK', 'indian', 'DCBBANK', 'DCB Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2100),
  ('NSE:DCMSHRIRAM', 'indian', 'DCMSHRIRAM', 'DCM Shriram', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2110),
  ('NSE:DEEPAKNTR', 'indian', 'DEEPAKNTR', 'Deepak Nitrite', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 250, null, 0.05, 'fno', 2120),
  ('NSE:DELHIVERY', 'indian', 'DELHIVERY', 'Delhivery', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2075, null, 0.05, 'fno', 2130),
  ('NSE:DEVYANI', 'indian', 'DEVYANI', 'Devyani International', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2140),
  ('NSE:DHAMPURSUG', 'indian', 'DHAMPURSUG', 'Dhampur Sugar Mills', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2150),
  ('NSE:DIVISLAB', 'indian', 'DIVISLAB', 'Divi''s Laboratories', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 100, null, 0.05, 'fno', 2160),
  ('NSE:DIXON', 'indian', 'DIXON', 'Dixon Technologies India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 50, null, 0.05, 'fno', 2170),
  ('NSE:DLF', 'indian', 'DLF', 'DLF', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 825, null, 0.05, 'fno', 2180),
  ('NSE:DMART', 'indian', 'DMART', 'Avenue Supermarts', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 2190),
  ('NSE:DRREDDY', 'indian', 'DRREDDY', 'Dr. Reddy''s Laboratories', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 625, null, 0.05, 'fno', 2200),
  ('NSE:EICHERMOT', 'indian', 'EICHERMOT', 'Eicher Motors', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 2210),
  ('NSE:EIDPARRY', 'indian', 'EIDPARRY', 'EID Parry India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2220),
  ('NSE:EIHOTEL', 'indian', 'EIHOTEL', 'EIH', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2230),
  ('NSE:ELGIEQUIP', 'indian', 'ELGIEQUIP', 'Elgi Equipments', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2240),
  ('NSE:EMAMILTD', 'indian', 'EMAMILTD', 'Emami', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2250),
  ('NSE:ENGINERSIN', 'indian', 'ENGINERSIN', 'Engineers India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2260),
  ('NSE:ERIS', 'indian', 'ERIS', 'Eris Lifesciences', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2270),
  ('NSE:ESCORTS', 'indian', 'ESCORTS', 'Escorts Kubota', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 2280),
  ('NSE:EXIDEIND', 'indian', 'EXIDEIND', 'Exide Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1800, null, 0.05, 'fno', 2290),
  ('NSE:FACT', 'indian', 'FACT', 'Fertilisers & Chemicals Travancore', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2300),
  ('NSE:FDC', 'indian', 'FDC', 'FDC', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2310),
  ('NSE:FEDERALBNK', 'indian', 'FEDERALBNK', 'Federal Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 5000, null, 0.05, 'fno', 2320),
  ('NSE:FINCABLES', 'indian', 'FINCABLES', 'Finolex Cables', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2330),
  ('NSE:FINEORG', 'indian', 'FINEORG', 'Fine Organic Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2340),
  ('NSE:FIRSTCRY', 'indian', 'FIRSTCRY', 'Brainbees Solutions (FirstCry)', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2350),
  ('NSE:FIVESTAR', 'indian', 'FIVESTAR', 'Five-Star Business Finance', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2360),
  ('NSE:FORTIS', 'indian', 'FORTIS', 'Fortis Healthcare', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1100, null, 0.05, 'fno', 2370),
  ('NSE:GAIL', 'indian', 'GAIL', 'GAIL India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3150, null, 0.05, 'fno', 2380),
  ('NSE:GALAXYSURF', 'indian', 'GALAXYSURF', 'Galaxy Surfactants', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2390),
  ('NSE:GATI', 'indian', 'GATI', 'Gati', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2400),
  ('NSE:GICRE', 'indian', 'GICRE', 'General Insurance Corporation of India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2410),
  ('NSE:GILLETTE', 'indian', 'GILLETTE', 'Gillette India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2420),
  ('NSE:GLAXO', 'indian', 'GLAXO', 'GlaxoSmithKline Pharmaceuticals', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2430),
  ('NSE:GLENMARK', 'indian', 'GLENMARK', 'Glenmark Pharmaceuticals', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 725, null, 0.05, 'fno', 2440),
  ('NSE:GMDCLTD', 'indian', 'GMDCLTD', 'Gujarat Mineral Development Corporation', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2450),
  ('NSE:GMRAIRPORT', 'indian', 'GMRAIRPORT', 'GMR Airports', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 5625, null, 0.05, 'fno', 2460),
  ('NSE:GNFC', 'indian', 'GNFC', 'Gujarat Narmada Valley Fertilizers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2470),
  ('NSE:GODAWARI', 'indian', 'GODAWARI', 'Godawari Power & Ispat', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2480),
  ('NSE:GODREJCP', 'indian', 'GODREJCP', 'Godrej Consumer Products', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 500, null, 0.05, 'fno', 2490),
  ('NSE:GODREJPROP', 'indian', 'GODREJPROP', 'Godrej Properties', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 275, null, 0.05, 'fno', 2500),
  ('NSE:GOKEX', 'indian', 'GOKEX', 'Gokaldas Exports', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2510),
  ('NSE:GPPL', 'indian', 'GPPL', 'Gujarat Pipavav Port', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2520),
  ('NSE:GRANULES', 'indian', 'GRANULES', 'Granules India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1350, null, 0.05, 'fno', 2530),
  ('NSE:GRAPHITE', 'indian', 'GRAPHITE', 'Graphite India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2540),
  ('NSE:GRASIM', 'indian', 'GRASIM', 'Grasim Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 250, null, 0.05, 'fno', 2550),
  ('NSE:GRAVITA', 'indian', 'GRAVITA', 'Gravita India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2560),
  ('NSE:GREENPANEL', 'indian', 'GREENPANEL', 'Greenpanel Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2570),
  ('NSE:GREENPLY', 'indian', 'GREENPLY', 'Greenply Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2580),
  ('NSE:GRINDWELL', 'indian', 'GRINDWELL', 'Grindwell Norton', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2590),
  ('NSE:GRINFRA', 'indian', 'GRINFRA', 'G R Infraprojects', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2600),
  ('NSE:GRSE', 'indian', 'GRSE', 'Garden Reach Shipbuilders & Engineers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2610),
  ('NSE:GSFC', 'indian', 'GSFC', 'Gujarat State Fertilizers & Chemicals', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2620),
  ('NSE:GSPL', 'indian', 'GSPL', 'Gujarat State Petronet', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2630),
  ('NSE:GUJALKALI', 'indian', 'GUJALKALI', 'Gujarat Alkalies & Chemicals', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2640),
  ('NSE:GUJGASLTD', 'indian', 'GUJGASLTD', 'Gujarat Gas', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1250, null, 0.05, 'fno', 2650),
  ('NSE:HAL', 'indian', 'HAL', 'Hindustan Aeronautics', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 2660),
  ('NSE:HAPPSTMNDS', 'indian', 'HAPPSTMNDS', 'Happiest Minds Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2670),
  ('NSE:HATSUN', 'indian', 'HATSUN', 'Hatsun Agro Product', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2680),
  ('NSE:HAVELLS', 'indian', 'HAVELLS', 'Havells India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 500, null, 0.05, 'fno', 2690),
  ('NSE:HBLENGINE', 'indian', 'HBLENGINE', 'HBL Engineering', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2700),
  ('NSE:HCLTECH', 'indian', 'HCLTECH', 'HCL Technologies', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 2710),
  ('NSE:HDFCAMC', 'indian', 'HDFCAMC', 'HDFC Asset Management Company', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 2720),
  ('NSE:HDFCBANK', 'indian', 'HDFCBANK', 'HDFC Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 550, null, 0.05, 'fno', 2730),
  ('NSE:HDFCLIFE', 'indian', 'HDFCLIFE', 'HDFC Life Insurance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1100, null, 0.05, 'fno', 2740),
  ('NSE:HEG', 'indian', 'HEG', 'HEG', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2750),
  ('NSE:HERITGFOOD', 'indian', 'HERITGFOOD', 'Heritage Foods', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2760),
  ('NSE:HEROMOTOCO', 'indian', 'HEROMOTOCO', 'Hero MotoCorp', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 300, null, 0.05, 'fno', 2770),
  ('NSE:HFCL', 'indian', 'HFCL', 'HFCL', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 6450, null, 0.05, 'fno', 2780),
  ('NSE:HGINFRA', 'indian', 'HGINFRA', 'H.G. Infra Engineering', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2790),
  ('NSE:HINDALCO', 'indian', 'HINDALCO', 'Hindalco Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1400, null, 0.05, 'fno', 2800),
  ('NSE:HINDCOPPER', 'indian', 'HINDCOPPER', 'Hindustan Copper', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2650, null, 0.05, 'fno', 2810),
  ('NSE:HINDPETRO', 'indian', 'HINDPETRO', 'Hindustan Petroleum Corporation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1800, null, 0.05, 'fno', 2820),
  ('NSE:HINDUNILVR', 'indian', 'HINDUNILVR', 'Hindustan Unilever', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 300, null, 0.05, 'fno', 2830),
  ('NSE:HINDZINC', 'indian', 'HINDZINC', 'Hindustan Zinc', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1225, null, 0.05, 'fno', 2840),
  ('NSE:HONAUT', 'indian', 'HONAUT', 'Honeywell Automation India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2850),
  ('NSE:HUDCO', 'indian', 'HUDCO', 'Housing & Urban Development Corporation', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2860),
  ('NSE:HYUNDAI', 'indian', 'HYUNDAI', 'Hyundai Motor India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2870),
  ('NSE:ICICIBANK', 'indian', 'ICICIBANK', 'ICICI Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 700, null, 0.05, 'fno', 2880),
  ('NSE:ICICIGI', 'indian', 'ICICIGI', 'ICICI Lombard General Insurance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 325, null, 0.05, 'fno', 2890),
  ('NSE:ICICIPRULI', 'indian', 'ICICIPRULI', 'ICICI Prudential Life Insurance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 925, null, 0.05, 'fno', 2900),
  ('NSE:IDEA', 'indian', 'IDEA', 'Vodafone Idea', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 50000, null, 0.05, 'fno', 2910),
  ('NSE:IDFC', 'indian', 'IDFC', 'IDFC', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2920),
  ('NSE:IDFCFIRSTB', 'indian', 'IDFCFIRSTB', 'IDFC First Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 9300, null, 0.05, 'fno', 2930),
  ('NSE:IEX', 'indian', 'IEX', 'Indian Energy Exchange', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3750, null, 0.05, 'fno', 2940),
  ('NSE:IGL', 'indian', 'IGL', 'Indraprastha Gas', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1375, null, 0.05, 'fno', 2950),
  ('NSE:IIFL', 'indian', 'IIFL', 'IIFL Finance', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 2960),
  ('NSE:INDHOTEL', 'indian', 'INDHOTEL', 'Indian Hotels Company', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 850, null, 0.05, 'fno', 2970),
  ('NSE:INDIAMART', 'indian', 'INDIAMART', 'IndiaMART InterMESH', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 300, null, 0.05, 'fno', 2980),
  ('NSE:INDIANB', 'indian', 'INDIANB', 'Indian Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 2990),
  ('NSE:INDIGO', 'indian', 'INDIGO', 'InterGlobe Aviation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 3000),
  ('NSE:INDOCO', 'indian', 'INDOCO', 'Indoco Remedies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3010),
  ('NSE:INDUSINDBK', 'indian', 'INDUSINDBK', 'IndusInd Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 700, null, 0.05, 'fno', 3020),
  ('NSE:INDUSTOWER', 'indian', 'INDUSTOWER', 'Indus Towers', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1700, null, 0.05, 'fno', 3030),
  ('NSE:INFY', 'indian', 'INFY', 'Infosys', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 3040),
  ('NSE:INOXINDIA', 'indian', 'INOXINDIA', 'Inox India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3050),
  ('NSE:INOXWIND', 'indian', 'INOXWIND', 'Inox Wind', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3060),
  ('NSE:INTELLECT', 'indian', 'INTELLECT', 'Intellect Design Arena', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3070),
  ('NSE:IOB', 'indian', 'IOB', 'Indian Overseas Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3080),
  ('NSE:IOC', 'indian', 'IOC', 'Indian Oil Corporation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 6500, null, 0.05, 'fno', 3090),
  ('NSE:IPCALAB', 'indian', 'IPCALAB', 'Ipca Laboratories', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 550, null, 0.05, 'fno', 3100),
  ('NSE:IRB', 'indian', 'IRB', 'IRB Infrastructure Developers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3110),
  ('NSE:IRCON', 'indian', 'IRCON', 'Ircon International', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3120),
  ('NSE:IRCTC', 'indian', 'IRCTC', 'Indian Railway Catering & Tourism', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 875, null, 0.05, 'fno', 3130),
  ('NSE:IRFC', 'indian', 'IRFC', 'Indian Railway Finance Corporation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 4250, null, 0.05, 'fno', 3140),
  ('NSE:ISGEC', 'indian', 'ISGEC', 'Isgec Heavy Engineering', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3150),
  ('NSE:ITC', 'indian', 'ITC', 'ITC', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1600, null, 0.05, 'fno', 3160),
  ('NSE:ITCHOTELS', 'indian', 'ITCHOTELS', 'ITC Hotels', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3170),
  ('NSE:ITI', 'indian', 'ITI', 'ITI', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3180),
  ('NSE:J&KBANK', 'indian', 'J&KBANK', 'Jammu & Kashmir Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3190),
  ('NSE:JBCHEPHARM', 'indian', 'JBCHEPHARM', 'JB Chemicals & Pharmaceuticals', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3200),
  ('NSE:JINDALSAW', 'indian', 'JINDALSAW', 'Jindal Saw', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3210),
  ('NSE:JINDALSTEL', 'indian', 'JINDALSTEL', 'Jindal Steel & Power', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 625, null, 0.05, 'fno', 3220),
  ('NSE:JIOFIN', 'indian', 'JIOFIN', 'Jio Financial Services', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2350, null, 0.05, 'fno', 3230),
  ('NSE:JKCEMENT', 'indian', 'JKCEMENT', 'JK Cement', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 125, null, 0.05, 'fno', 3240),
  ('NSE:JKPAPER', 'indian', 'JKPAPER', 'JK Paper', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3250),
  ('NSE:JSL', 'indian', 'JSL', 'Jindal Stainless', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 850, null, 0.05, 'fno', 3260),
  ('NSE:JSWENERGY', 'indian', 'JSWENERGY', 'JSW Energy', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 3270),
  ('NSE:JSWINFRA', 'indian', 'JSWINFRA', 'JSW Infrastructure', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3280),
  ('NSE:JSWSTEEL', 'indian', 'JSWSTEEL', 'JSW Steel', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 675, null, 0.05, 'fno', 3290),
  ('NSE:JUBLFOOD', 'indian', 'JUBLFOOD', 'Jubilant FoodWorks', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1250, null, 0.05, 'fno', 3300),
  ('NSE:JUBLINGREA', 'indian', 'JUBLINGREA', 'Jubilant Ingrevia', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3310),
  ('NSE:JUBLPHARMA', 'indian', 'JUBLPHARMA', 'Jubilant Pharmova', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3320),
  ('NSE:JUSTDIAL', 'indian', 'JUSTDIAL', 'Just Dial', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3330),
  ('NSE:JWL', 'indian', 'JWL', 'Jupiter Wagons', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3340),
  ('NSE:JYOTHYLAB', 'indian', 'JYOTHYLAB', 'Jyothy Labs', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3350),
  ('NSE:JYOTICNC', 'indian', 'JYOTICNC', 'Jyoti CNC Automation', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3360),
  ('NSE:KAJARIACER', 'indian', 'KAJARIACER', 'Kajaria Ceramics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3370),
  ('NSE:KALYANKJIL', 'indian', 'KALYANKJIL', 'Kalyan Jewellers India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1175, null, 0.05, 'fno', 3380),
  ('NSE:KANSAINER', 'indian', 'KANSAINER', 'Kansai Nerolac Paints', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3390),
  ('NSE:KARURVYSYA', 'indian', 'KARURVYSYA', 'Karur Vysya Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3400),
  ('NSE:KAYNES', 'indian', 'KAYNES', 'Kaynes Technology India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3410),
  ('NSE:KEI', 'indian', 'KEI', 'KEI Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 3420),
  ('NSE:KFINTECH', 'indian', 'KFINTECH', 'KFin Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3430),
  ('NSE:KIMS', 'indian', 'KIMS', 'Krishna Institute of Medical Sciences', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3440),
  ('NSE:KIRLOSBROS', 'indian', 'KIRLOSBROS', 'Kirloskar Brothers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3450),
  ('NSE:KIRLOSENG', 'indian', 'KIRLOSENG', 'Kirloskar Oil Engines', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3460),
  ('NSE:KNRCON', 'indian', 'KNRCON', 'KNR Constructions', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3470),
  ('NSE:KOLTEPATIL', 'indian', 'KOLTEPATIL', 'Kolte-Patil Developers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3480),
  ('NSE:KOTAKBANK', 'indian', 'KOTAKBANK', 'Kotak Mahindra Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 3490),
  ('NSE:KPIGREEN', 'indian', 'KPIGREEN', 'KPI Green Energy', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3500),
  ('NSE:KPITTECH', 'indian', 'KPITTECH', 'KPIT Technologies', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 3510),
  ('NSE:KPRMILL', 'indian', 'KPRMILL', 'K.P.R. Mill', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3520),
  ('NSE:KRBL', 'indian', 'KRBL', 'KRBL', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3530),
  ('NSE:LALPATHLAB', 'indian', 'LALPATHLAB', 'Dr. Lal PathLabs', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3540),
  ('NSE:LATENTVIEW', 'indian', 'LATENTVIEW', 'Latent View Analytics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3550),
  ('NSE:LAURUSLABS', 'indian', 'LAURUSLABS', 'Laurus Labs', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1700, null, 0.05, 'fno', 3560),
  ('NSE:LEMONTREE', 'indian', 'LEMONTREE', 'Lemon Tree Hotels', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3570),
  ('NSE:LICHSGFIN', 'indian', 'LICHSGFIN', 'LIC Housing Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 3580),
  ('NSE:LICI', 'indian', 'LICI', 'Life Insurance Corporation of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 700, null, 0.05, 'fno', 3590),
  ('NSE:LINDEINDIA', 'indian', 'LINDEINDIA', 'Linde India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3600),
  ('NSE:LLOYDSME', 'indian', 'LLOYDSME', 'Lloyds Metals & Energy', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3610),
  ('NSE:LODHA', 'indian', 'LODHA', 'Macrotech Developers', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 450, null, 0.05, 'fno', 3620),
  ('NSE:LT', 'indian', 'LT', 'Larsen & Toubro', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 3630),
  ('NSE:LTF', 'indian', 'LTF', 'L&T Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3875, null, 0.05, 'fno', 3640),
  ('NSE:LTIM', 'indian', 'LTIM', 'LTIMindtree', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 3650),
  ('NSE:LUPIN', 'indian', 'LUPIN', 'Lupin', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 425, null, 0.05, 'fno', 3660),
  ('NSE:M&M', 'indian', 'M&M', 'Mahindra & Mahindra', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 3670),
  ('NSE:M&MFIN', 'indian', 'M&MFIN', 'Mahindra & Mahindra Financial Services', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2300, null, 0.05, 'fno', 3680),
  ('NSE:MAHABANK', 'indian', 'MAHABANK', 'Bank of Maharashtra', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3690),
  ('NSE:MAHLIFE', 'indian', 'MAHLIFE', 'Mahindra Lifespace Developers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3700),
  ('NSE:MAHLOG', 'indian', 'MAHLOG', 'Mahindra Logistics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3710),
  ('NSE:MAHSEAMLES', 'indian', 'MAHSEAMLES', 'Maharashtra Seamless', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3720),
  ('NSE:MANAPPURAM', 'indian', 'MANAPPURAM', 'Manappuram Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3000, null, 0.05, 'fno', 3730),
  ('NSE:MANKIND', 'indian', 'MANKIND', 'Mankind Pharma', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 225, null, 0.05, 'fno', 3740),
  ('NSE:MAPMYINDIA', 'indian', 'MAPMYINDIA', 'C.E. Info Systems (MapmyIndia)', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3750),
  ('NSE:MARICO', 'indian', 'MARICO', 'Marico', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1200, null, 0.05, 'fno', 3760),
  ('NSE:MARKSANS', 'indian', 'MARKSANS', 'Marksans Pharma', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3770),
  ('NSE:MARUTI', 'indian', 'MARUTI', 'Maruti Suzuki India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 50, null, 0.05, 'fno', 3780),
  ('NSE:MASTEK', 'indian', 'MASTEK', 'Mastek', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3790),
  ('NSE:MAXHEALTH', 'indian', 'MAXHEALTH', 'Max Healthcare Institute', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 525, null, 0.05, 'fno', 3800),
  ('NSE:MAZDOCK', 'indian', 'MAZDOCK', 'Mazagon Dock Shipbuilders', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3810),
  ('NSE:MCX', 'indian', 'MCX', 'Multi Commodity Exchange of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 3820),
  ('NSE:MEDANTA', 'indian', 'MEDANTA', 'Global Health (Medanta)', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3830),
  ('NSE:METROPOLIS', 'indian', 'METROPOLIS', 'Metropolis Healthcare', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3840),
  ('NSE:MGL', 'indian', 'MGL', 'Mahanagar Gas', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 3850),
  ('NSE:MOBIKWIK', 'indian', 'MOBIKWIK', 'One MobiKwik Systems', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3860),
  ('NSE:MOIL', 'indian', 'MOIL', 'MOIL', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3870),
  ('NSE:MOREPENLAB', 'indian', 'MOREPENLAB', 'Morepen Laboratories', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3880),
  ('NSE:MOTHERSON', 'indian', 'MOTHERSON', 'Samvardhana Motherson International', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3800, null, 0.05, 'fno', 3890),
  ('NSE:MOTILALOFS', 'indian', 'MOTILALOFS', 'Motilal Oswal Financial Services', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3900),
  ('NSE:MPHASIS', 'indian', 'MPHASIS', 'Mphasis', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 275, null, 0.05, 'fno', 3910),
  ('NSE:MRF', 'indian', 'MRF', 'MRF', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 5, null, 0.05, 'fno', 3920),
  ('NSE:MUTHOOTFIN', 'indian', 'MUTHOOTFIN', 'Muthoot Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 275, null, 0.05, 'fno', 3930),
  ('NSE:NAM-INDIA', 'indian', 'NAM-INDIA', 'Nippon Life India Asset Management', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3940),
  ('NSE:NATCOPHARM', 'indian', 'NATCOPHARM', 'Natco Pharma', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3950),
  ('NSE:NATIONALUM', 'indian', 'NATIONALUM', 'National Aluminium Company', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3750, null, 0.05, 'fno', 3960),
  ('NSE:NAUKRI', 'indian', 'NAUKRI', 'Info Edge India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 375, null, 0.05, 'fno', 3970),
  ('NSE:NAVINFLUOR', 'indian', 'NAVINFLUOR', 'Navin Fluorine International', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 150, null, 0.05, 'fno', 3980),
  ('NSE:NBCC', 'indian', 'NBCC', 'NBCC India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 3990),
  ('NSE:NCC', 'indian', 'NCC', 'NCC', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4000),
  ('NSE:NESTLEIND', 'indian', 'NESTLEIND', 'Nestle India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 250, null, 0.05, 'fno', 4010),
  ('NSE:NETWEB', 'indian', 'NETWEB', 'Netweb Technologies India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4020),
  ('NSE:NEULANDLAB', 'indian', 'NEULANDLAB', 'Neuland Laboratories', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4030),
  ('NSE:NEWGEN', 'indian', 'NEWGEN', 'Newgen Software Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4040),
  ('NSE:NH', 'indian', 'NH', 'Narayana Hrudayalaya', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4050),
  ('NSE:NHPC', 'indian', 'NHPC', 'NHPC', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 6400, null, 0.05, 'fno', 4060),
  ('NSE:NIACL', 'indian', 'NIACL', 'New India Assurance Company', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4070),
  ('NSE:NIVABUPA', 'indian', 'NIVABUPA', 'Niva Bupa Health Insurance', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4080),
  ('NSE:NMDC', 'indian', 'NMDC', 'NMDC', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 4500, null, 0.05, 'fno', 4090),
  ('NSE:NTPC', 'indian', 'NTPC', 'NTPC', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1500, null, 0.05, 'fno', 4100),
  ('NSE:NTPCGREEN', 'indian', 'NTPCGREEN', 'NTPC Green Energy', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4110),
  ('NSE:NUVAMA', 'indian', 'NUVAMA', 'Nuvama Wealth Management', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4120),
  ('NSE:NYKAA', 'indian', 'NYKAA', 'FSN E-Commerce Ventures (Nykaa)', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3125, null, 0.05, 'fno', 4130),
  ('NSE:OBEROIRLTY', 'indian', 'OBEROIRLTY', 'Oberoi Realty', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 4140),
  ('NSE:OFSS', 'indian', 'OFSS', 'Oracle Financial Services Software', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 75, null, 0.05, 'fno', 4150),
  ('NSE:OIL', 'indian', 'OIL', 'Oil India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1400, null, 0.05, 'fno', 4160),
  ('NSE:OLAELEC', 'indian', 'OLAELEC', 'Ola Electric Mobility', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4170),
  ('NSE:ONGC', 'indian', 'ONGC', 'Oil & Natural Gas Corporation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2250, null, 0.05, 'fno', 4180),
  ('NSE:ORCHPHARMA', 'indian', 'ORCHPHARMA', 'Orchid Pharma', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4190),
  ('NSE:PAGEIND', 'indian', 'PAGEIND', 'Page Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 15, null, 0.05, 'fno', 4200),
  ('NSE:PARADEEP', 'indian', 'PARADEEP', 'Paradeep Phosphates', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4210),
  ('NSE:PARAS', 'indian', 'PARAS', 'Paras Defence & Space Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4220),
  ('NSE:PATANJALI', 'indian', 'PATANJALI', 'Patanjali Foods', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4230),
  ('NSE:PAYTM', 'indian', 'PAYTM', 'One97 Communications (Paytm)', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 725, null, 0.05, 'fno', 4240),
  ('NSE:PEL', 'indian', 'PEL', 'Piramal Enterprises', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 600, null, 0.05, 'fno', 4250),
  ('NSE:PERSISTENT', 'indian', 'PERSISTENT', 'Persistent Systems', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 100, null, 0.05, 'fno', 4260),
  ('NSE:PETRONET', 'indian', 'PETRONET', 'Petronet LNG', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1800, null, 0.05, 'fno', 4270),
  ('NSE:PFC', 'indian', 'PFC', 'Power Finance Corporation', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1300, null, 0.05, 'fno', 4280),
  ('NSE:PFIZER', 'indian', 'PFIZER', 'Pfizer', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4290),
  ('NSE:PGHH', 'indian', 'PGHH', 'Procter & Gamble Hygiene & Health Care', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4300),
  ('NSE:PHOENIXLTD', 'indian', 'PHOENIXLTD', 'Phoenix Mills', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4310),
  ('NSE:PIDILITIND', 'indian', 'PIDILITIND', 'Pidilite Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 250, null, 0.05, 'fno', 4320),
  ('NSE:PIIND', 'indian', 'PIIND', 'PI Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 4330),
  ('NSE:PNB', 'indian', 'PNB', 'Punjab National Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 8000, null, 0.05, 'fno', 4340),
  ('NSE:PNCINFRA', 'indian', 'PNCINFRA', 'PNC Infratech', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4350),
  ('NSE:POLICYBZR', 'indian', 'POLICYBZR', 'PB Fintech', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 4360),
  ('NSE:POLYCAB', 'indian', 'POLYCAB', 'Polycab India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 100, null, 0.05, 'fno', 4370),
  ('NSE:POONAWALLA', 'indian', 'POONAWALLA', 'Poonawalla Fincorp', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4380),
  ('NSE:POWERGRID', 'indian', 'POWERGRID', 'Power Grid Corporation of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1900, null, 0.05, 'fno', 4390),
  ('NSE:PPLPHARMA', 'indian', 'PPLPHARMA', 'Piramal Pharma', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4400),
  ('NSE:PRAJIND', 'indian', 'PRAJIND', 'Praj Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4410),
  ('NSE:PREMIERENE', 'indian', 'PREMIERENE', 'Premier Energies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4420),
  ('NSE:PRESTIGE', 'indian', 'PRESTIGE', 'Prestige Estates Projects', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 425, null, 0.05, 'fno', 4430),
  ('NSE:PSB', 'indian', 'PSB', 'Punjab & Sind Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4440),
  ('NSE:PVRINOX', 'indian', 'PVRINOX', 'PVR INOX', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 407, null, 0.05, 'fno', 4450),
  ('NSE:RADICO', 'indian', 'RADICO', 'Radico Khaitan', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4460),
  ('NSE:RAILTEL', 'indian', 'RAILTEL', 'RailTel Corporation of India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4470),
  ('NSE:RAINBOW', 'indian', 'RAINBOW', 'Rainbow Children''s Medicare', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4480),
  ('NSE:RALLIS', 'indian', 'RALLIS', 'Rallis India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4490),
  ('NSE:RAMCOCEM', 'indian', 'RAMCOCEM', 'Ramco Cements', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 850, null, 0.05, 'fno', 4500),
  ('NSE:RATEGAIN', 'indian', 'RATEGAIN', 'RateGain Travel Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4510),
  ('NSE:RATNAMANI', 'indian', 'RATNAMANI', 'Ratnamani Metals & Tubes', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4520),
  ('NSE:RAYMOND', 'indian', 'RAYMOND', 'Raymond', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4530),
  ('NSE:RBLBANK', 'indian', 'RBLBANK', 'RBL Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3175, null, 0.05, 'fno', 4540),
  ('NSE:RCF', 'indian', 'RCF', 'Rashtriya Chemicals & Fertilizers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4550),
  ('NSE:RECLTD', 'indian', 'RECLTD', 'REC', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1125, null, 0.05, 'fno', 4560),
  ('NSE:RELAXO', 'indian', 'RELAXO', 'Relaxo Footwears', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4570),
  ('NSE:RELIANCE', 'indian', 'RELIANCE', 'Reliance Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 500, null, 0.05, 'fno', 4580),
  ('NSE:RITES', 'indian', 'RITES', 'RITES', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4590),
  ('NSE:ROUTE', 'indian', 'ROUTE', 'Route Mobile', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4600),
  ('NSE:RRKABEL', 'indian', 'RRKABEL', 'R R Kabel', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4610),
  ('NSE:RVNL', 'indian', 'RVNL', 'Rail Vikas Nigam', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1475, null, 0.05, 'fno', 4620),
  ('NSE:SAIL', 'indian', 'SAIL', 'Steel Authority of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 4000, null, 0.05, 'fno', 4630),
  ('NSE:SANDUMA', 'indian', 'SANDUMA', 'Sandur Manganese & Iron Ores', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4640),
  ('NSE:SANOFI', 'indian', 'SANOFI', 'Sanofi India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4650),
  ('NSE:SAPPHIRE', 'indian', 'SAPPHIRE', 'Sapphire Foods India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4660),
  ('NSE:SBICARD', 'indian', 'SBICARD', 'SBI Cards & Payment Services', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 800, null, 0.05, 'fno', 4670),
  ('NSE:SBILIFE', 'indian', 'SBILIFE', 'SBI Life Insurance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 375, null, 0.05, 'fno', 4680),
  ('NSE:SBIN', 'indian', 'SBIN', 'State Bank of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 750, null, 0.05, 'fno', 4690),
  ('NSE:SCHAEFFLER', 'indian', 'SCHAEFFLER', 'Schaeffler India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4700),
  ('NSE:SCI', 'indian', 'SCI', 'Shipping Corporation of India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4710),
  ('NSE:SENCO', 'indian', 'SENCO', 'Senco Gold', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4720),
  ('NSE:SEQUENT', 'indian', 'SEQUENT', 'Sequent Scientific', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4730),
  ('NSE:SHARDACROP', 'indian', 'SHARDACROP', 'Sharda Cropchem', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4740),
  ('NSE:SHILPAMED', 'indian', 'SHILPAMED', 'Shilpa Medicare', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4750),
  ('NSE:SHOPERSTOP', 'indian', 'SHOPERSTOP', 'Shoppers Stop', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4760),
  ('NSE:SHREECEM', 'indian', 'SHREECEM', 'Shree Cement', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 25, null, 0.05, 'fno', 4770),
  ('NSE:SHRIRAMFIN', 'indian', 'SHRIRAMFIN', 'Shriram Finance', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1100, null, 0.05, 'fno', 4780),
  ('NSE:SHYAMMETL', 'indian', 'SHYAMMETL', 'Shyam Metalics & Energy', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4790),
  ('NSE:SIEMENS', 'indian', 'SIEMENS', 'Siemens', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 75, null, 0.05, 'fno', 4800),
  ('NSE:SIGNATURE', 'indian', 'SIGNATURE', 'Signatureglobal India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4810),
  ('NSE:SJVN', 'indian', 'SJVN', 'SJVN', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 5000, null, 0.05, 'fno', 4820),
  ('NSE:SKFINDIA', 'indian', 'SKFINDIA', 'SKF India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4830),
  ('NSE:SOBHA', 'indian', 'SOBHA', 'Sobha', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4840),
  ('NSE:SOLARA', 'indian', 'SOLARA', 'Solara Active Pharma Sciences', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4850),
  ('NSE:SOLARINDS', 'indian', 'SOLARINDS', 'Solar Industries India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4860),
  ('NSE:SONATSOFTW', 'indian', 'SONATSOFTW', 'Sonata Software', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4870),
  ('NSE:SOUTHBANK', 'indian', 'SOUTHBANK', 'South Indian Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4880),
  ('NSE:SPICEJET', 'indian', 'SPICEJET', 'SpiceJet', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4890),
  ('NSE:SRF', 'indian', 'SRF', 'SRF', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 4900),
  ('NSE:STAR', 'indian', 'STAR', 'Strides Pharma Science', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4910),
  ('NSE:STARHEALTH', 'indian', 'STARHEALTH', 'Star Health & Allied Insurance', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4920),
  ('NSE:STLTECH', 'indian', 'STLTECH', 'Sterlite Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4930),
  ('NSE:SUMICHEM', 'indian', 'SUMICHEM', 'Sumitomo Chemical India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4940),
  ('NSE:SUNDARMFIN', 'indian', 'SUNDARMFIN', 'Sundaram Finance', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4950),
  ('NSE:SUNPHARMA', 'indian', 'SUNPHARMA', 'Sun Pharmaceutical Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 4960),
  ('NSE:SUNTECK', 'indian', 'SUNTECK', 'Sunteck Realty', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 4970),
  ('NSE:SUNTV', 'indian', 'SUNTV', 'Sun TV Network', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1500, null, 0.05, 'fno', 4980),
  ('NSE:SUPREMEIND', 'indian', 'SUPREMEIND', 'Supreme Industries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 4990),
  ('NSE:SUVENPHAR', 'indian', 'SUVENPHAR', 'Suven Pharmaceuticals', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5000),
  ('NSE:SUZLON', 'indian', 'SUZLON', 'Suzlon Energy', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 8000, null, 0.05, 'fno', 5010),
  ('NSE:SWIGGY', 'indian', 'SWIGGY', 'Swiggy', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5020),
  ('NSE:SYMPHONY', 'indian', 'SYMPHONY', 'Symphony', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5030),
  ('NSE:SYNGENE', 'indian', 'SYNGENE', 'Syngene International', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 5040),
  ('NSE:SYRMA', 'indian', 'SYRMA', 'Syrma SGS Technology', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5050),
  ('NSE:TANLA', 'indian', 'TANLA', 'Tanla Platforms', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1000, null, 0.05, 'fno', 5060),
  ('NSE:TATACHEM', 'indian', 'TATACHEM', 'Tata Chemicals', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 550, null, 0.05, 'fno', 5070),
  ('NSE:TATACOFFEE', 'indian', 'TATACOFFEE', 'Tata Coffee', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5080),
  ('NSE:TATACOMM', 'indian', 'TATACOMM', 'Tata Communications', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 5090),
  ('NSE:TATACONSUM', 'indian', 'TATACONSUM', 'Tata Consumer Products', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 550, null, 0.05, 'fno', 5100),
  ('NSE:TATAELXSI', 'indian', 'TATAELXSI', 'Tata Elxsi', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 100, null, 0.05, 'fno', 5110),
  ('NSE:TATAINVEST', 'indian', 'TATAINVEST', 'Tata Investment Corporation', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5120),
  ('NSE:TATAMOTORS', 'indian', 'TATAMOTORS', 'Tata Motors', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 800, null, 0.05, 'fno', 5130),
  ('NSE:TATAPOWER', 'indian', 'TATAPOWER', 'Tata Power Company', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1450, null, 0.05, 'fno', 5140),
  ('NSE:TATASTEEL', 'indian', 'TATASTEEL', 'Tata Steel', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 5500, null, 0.05, 'fno', 5150),
  ('NSE:TATATECH', 'indian', 'TATATECH', 'Tata Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5160),
  ('NSE:TCIEXP', 'indian', 'TCIEXP', 'TCI Express', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5170),
  ('NSE:TCS', 'indian', 'TCS', 'Tata Consultancy Services', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 5180),
  ('NSE:TECHM', 'indian', 'TECHM', 'Tech Mahindra', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 600, null, 0.05, 'fno', 5190),
  ('NSE:TEJASNET', 'indian', 'TEJASNET', 'Tejas Networks', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5200),
  ('NSE:TEXRAIL', 'indian', 'TEXRAIL', 'Texmaco Rail & Engineering', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5210),
  ('NSE:THANGAMAYL', 'indian', 'THANGAMAYL', 'Thangamayil Jewellery', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5220),
  ('NSE:THERMAX', 'indian', 'THERMAX', 'Thermax', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5230),
  ('NSE:THYROCARE', 'indian', 'THYROCARE', 'Thyrocare Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5240),
  ('NSE:TIINDIA', 'indian', 'TIINDIA', 'Tube Investments of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 200, null, 0.05, 'fno', 5250),
  ('NSE:TIMKEN', 'indian', 'TIMKEN', 'Timken India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5260),
  ('NSE:TITAGARH', 'indian', 'TITAGARH', 'Titagarh Rail Systems', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5270),
  ('NSE:TITAN', 'indian', 'TITAN', 'Titan Company', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 175, null, 0.05, 'fno', 5280),
  ('NSE:TORNTPHARM', 'indian', 'TORNTPHARM', 'Torrent Pharmaceuticals', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 250, null, 0.05, 'fno', 5290),
  ('NSE:TORNTPOWER', 'indian', 'TORNTPOWER', 'Torrent Power', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 375, null, 0.05, 'fno', 5300),
  ('NSE:TRANSFORMER', 'indian', 'TRANSFORMER', 'Transformers & Rectifiers India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5310),
  ('NSE:TRENT', 'indian', 'TRENT', 'Trent', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 100, null, 0.05, 'fno', 5320),
  ('NSE:TRIDENT', 'indian', 'TRIDENT', 'Trident', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5330),
  ('NSE:TRITURBINE', 'indian', 'TRITURBINE', 'Triveni Turbine', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5340),
  ('NSE:TRIVENI', 'indian', 'TRIVENI', 'Triveni Engineering & Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5350),
  ('NSE:TTKPRESTIG', 'indian', 'TTKPRESTIG', 'TTK Prestige', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5360),
  ('NSE:TVSMOTOR', 'indian', 'TVSMOTOR', 'TVS Motor Company', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 350, null, 0.05, 'fno', 5370),
  ('NSE:UBL', 'indian', 'UBL', 'United Breweries', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 5380),
  ('NSE:UCOBANK', 'indian', 'UCOBANK', 'UCO Bank', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5390),
  ('NSE:ULTRACEMCO', 'indian', 'ULTRACEMCO', 'UltraTech Cement', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 50, null, 0.05, 'fno', 5400),
  ('NSE:UNICHEMLAB', 'indian', 'UNICHEMLAB', 'Unichem Laboratories', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5410),
  ('NSE:UNIONBANK', 'indian', 'UNIONBANK', 'Union Bank of India', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 4200, null, 0.05, 'fno', 5420),
  ('NSE:UNITDSPR', 'indian', 'UNITDSPR', 'United Spirits', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 400, null, 0.05, 'fno', 5430),
  ('NSE:UPL', 'indian', 'UPL', 'UPL', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1355, null, 0.05, 'fno', 5440),
  ('NSE:UTIAMC', 'indian', 'UTIAMC', 'UTI Asset Management Company', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5450),
  ('NSE:VBL', 'indian', 'VBL', 'Varun Beverages', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1025, null, 0.05, 'fno', 5460),
  ('NSE:VEDL', 'indian', 'VEDL', 'Vedanta', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 1150, null, 0.05, 'fno', 5470),
  ('NSE:VENUSREM', 'indian', 'VENUSREM', 'Venus Remedies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5480),
  ('NSE:VGUARD', 'indian', 'VGUARD', 'V-Guard Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5490),
  ('NSE:VINATIORGA', 'indian', 'VINATIORGA', 'Vinati Organics', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5500),
  ('NSE:VIPIND', 'indian', 'VIPIND', 'VIP Industries', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5510),
  ('NSE:VMART', 'indian', 'VMART', 'V-Mart Retail', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5520),
  ('NSE:VOLTAMP', 'indian', 'VOLTAMP', 'Voltamp Transformers', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5530),
  ('NSE:VOLTAS', 'indian', 'VOLTAS', 'Voltas', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 375, null, 0.05, 'fno', 5540),
  ('NSE:VTL', 'indian', 'VTL', 'Vardhman Textiles', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5550),
  ('NSE:WAAREEENER', 'indian', 'WAAREEENER', 'Waaree Energies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5560),
  ('NSE:WELCORP', 'indian', 'WELCORP', 'Welspun Corp', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5570),
  ('NSE:WELSPUNLIV', 'indian', 'WELSPUNLIV', 'Welspun Living', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5580),
  ('NSE:WESTLIFE', 'indian', 'WESTLIFE', 'Westlife Foodworld', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5590),
  ('NSE:WHIRLPOOL', 'indian', 'WHIRLPOOL', 'Whirlpool of India', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5600),
  ('NSE:WIPRO', 'indian', 'WIPRO', 'Wipro', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 3000, null, 0.05, 'fno', 5610),
  ('NSE:WOCKPHARMA', 'indian', 'WOCKPHARMA', 'Wockhardt', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5620),
  ('NSE:WSTCSTPAPR', 'indian', 'WSTCSTPAPR', 'West Coast Paper Mills', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5630),
  ('NSE:YESBANK', 'indian', 'YESBANK', 'Yes Bank', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 31100, null, 0.05, 'fno', 5640),
  ('NSE:ZENSARTECH', 'indian', 'ZENSARTECH', 'Zensar Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5650),
  ('NSE:ZENTEC', 'indian', 'ZENTEC', 'Zen Technologies', 'NSE', array['BSE']::text[], 'EQ', false, null, 'INR', 1, 1, null, 0.05, 'cash', 5660),
  ('NSE:ZOMATO', 'indian', 'ZOMATO', 'Eternal (Zomato)', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 2425, null, 0.05, 'fno', 5670),
  ('NSE:ZYDUSLIFE', 'indian', 'ZYDUSLIFE', 'Zydus Lifesciences', 'NSE', array['BSE']::text[], 'EQ', true, null, 'INR', 1, 900, null, 0.05, 'fno', 5680)
on conflict (id) do update set
  name           = excluded.name,
  exchange       = excluded.exchange,
  also_on        = excluded.also_on,
  segment        = excluded.segment,
  has_fno        = excluded.has_fno,
  base_currency  = excluded.base_currency,
  quote_currency = excluded.quote_currency,
  contract_size  = excluded.contract_size,
  lot_size       = excluded.lot_size,
  pip_size       = excluded.pip_size,
  tick_size      = excluded.tick_size,
  category       = excluded.category,
  sort_order     = excluded.sort_order,
  is_active      = true;

-- Retire anything the Phase 1 starter seed created that is no longer in the
-- dataset (deactivated, not deleted, so existing trades keep resolving their
-- symbol).
update public.instruments
   set is_active = false
 where id not in (
   'FX:EURUSD',
   'FX:GBPUSD',
   'FX:USDJPY',
   'FX:USDCHF',
   'FX:AUDUSD',
   'FX:USDCAD',
   'FX:NZDUSD',
   'FX:EURGBP',
   'FX:EURJPY',
   'FX:EURCHF',
   'FX:EURAUD',
   'FX:EURCAD',
   'FX:EURNZD',
   'FX:GBPJPY',
   'FX:GBPCHF',
   'FX:GBPAUD',
   'FX:GBPCAD',
   'FX:GBPNZD',
   'FX:AUDJPY',
   'FX:AUDCHF',
   'FX:AUDCAD',
   'FX:AUDNZD',
   'FX:NZDJPY',
   'FX:NZDCHF',
   'FX:NZDCAD',
   'FX:CADJPY',
   'FX:CADCHF',
   'FX:CHFJPY',
   'FX:USDINR',
   'FX:EURINR',
   'FX:GBPINR',
   'FX:JPYINR',
   'FX:USDSGD',
   'FX:USDHKD',
   'FX:USDCNH',
   'FX:USDZAR',
   'FX:USDMXN',
   'FX:USDTRY',
   'FX:USDNOK',
   'FX:USDSEK',
   'FX:USDDKK',
   'FX:USDPLN',
   'FX:USDCZK',
   'FX:USDHUF',
   'FX:USDTHB',
   'FX:USDAED',
   'FX:USDSAR',
   'FX:USDILS',
   'FX:USDBRL',
   'FX:USDPHP',
   'FX:USDTWD',
   'FX:USDKRW',
   'FX:EURTRY',
   'FX:EURZAR',
   'FX:EURMXN',
   'FX:EURNOK',
   'FX:EURSEK',
   'FX:EURPLN',
   'FX:EURHUF',
   'FX:EURCZK',
   'FX:EURSGD',
   'FX:GBPZAR',
   'FX:GBPSGD',
   'FX:AUDSGD',
   'FX:SGDJPY',
   'FX:ZARJPY',
   'FX:TRYJPY',
   'FX:NOKSEK',
   'FX:XAUUSD',
   'FX:XAGUSD',
   'FX:XPTUSD',
   'FX:XPDUSD',
   'FX:XAUEUR',
   'FX:BTCUSD',
   'FX:ETHUSD',
   'FX:XRPUSD',
   'FX:SOLUSD',
   'FX:LTCUSD',
   'NSE:NIFTY',
   'NSE:BANKNIFTY',
   'NSE:FINNIFTY',
   'NSE:MIDCPNIFTY',
   'NSE:NIFTYNXT50',
   'BSE:SENSEX',
   'BSE:BANKEX',
   'BSE:SENSEX50',
   'NSE:360ONE',
   'NSE:3MINDIA',
   'NSE:AARTIIND',
   'NSE:ABB',
   'NSE:ABBOTINDIA',
   'NSE:ABCAPITAL',
   'NSE:ABFRL',
   'NSE:ABSLAMC',
   'NSE:ACC',
   'NSE:ADANIENSOL',
   'NSE:ADANIENT',
   'NSE:ADANIGREEN',
   'NSE:ADANIPORTS',
   'NSE:ADANIPOWER',
   'NSE:AEGISLOG',
   'NSE:AFFLE',
   'NSE:AHLUCONT',
   'NSE:AIAENG',
   'NSE:AJANTPHARM',
   'NSE:AKZOINDIA',
   'NSE:ALKEM',
   'NSE:ALKYLAMINE',
   'NSE:ALLCARGO',
   'NSE:AMBER',
   'NSE:AMBUJACEM',
   'NSE:ANANDRATHI',
   'NSE:ANANTRAJ',
   'NSE:ANGELONE',
   'NSE:APARINDS',
   'NSE:APLAPOLLO',
   'NSE:APOLLOHOSP',
   'NSE:APOLLOTYRE',
   'NSE:ARVIND',
   'NSE:ASHOKLEY',
   'NSE:ASIANPAINT',
   'NSE:ASTERDM',
   'NSE:ASTRAL',
   'NSE:ASTRAMICRO',
   'NSE:ATGL',
   'NSE:ATUL',
   'NSE:AUBANK',
   'NSE:AUROPHARMA',
   'NSE:AVALON',
   'NSE:AVANTIFEED',
   'NSE:AWL',
   'NSE:AXISBANK',
   'NSE:AZAD',
   'NSE:BAJAJ-AUTO',
   'NSE:BAJAJFINSV',
   'NSE:BAJAJHLDNG',
   'NSE:BAJFINANCE',
   'NSE:BALAMINES',
   'NSE:BALKRISIND',
   'NSE:BALRAMCHIN',
   'NSE:BANDHANBNK',
   'NSE:BANKBARODA',
   'NSE:BARBEQUE',
   'NSE:BATAINDIA',
   'NSE:BAYERCROP',
   'NSE:BDL',
   'NSE:BEL',
   'NSE:BEML',
   'NSE:BERGEPAINT',
   'NSE:BHARATFORG',
   'NSE:BHARTIARTL',
   'NSE:BHEL',
   'NSE:BIKAJI',
   'NSE:BIOCON',
   'NSE:BLISSGVS',
   'NSE:BLUEDART',
   'NSE:BLUESTARCO',
   'NSE:BORORENEW',
   'NSE:BOSCHLTD',
   'NSE:BPCL',
   'NSE:BRIGADE',
   'NSE:BRITANNIA',
   'NSE:BSE',
   'NSE:BSOFT',
   'NSE:CAMLINFINE',
   'NSE:CAMS',
   'NSE:CANBK',
   'NSE:CAPLIPOINT',
   'NSE:CARBORUNIV',
   'NSE:CASTROLIND',
   'NSE:CCL',
   'NSE:CDSL',
   'NSE:CENTRALBK',
   'NSE:CENTURYPLY',
   'NSE:CERA',
   'NSE:CGPOWER',
   'NSE:CHALET',
   'NSE:CHAMBLFERT',
   'NSE:CHOLAFIN',
   'NSE:CIPLA',
   'NSE:CLEAN',
   'NSE:COALINDIA',
   'NSE:COCHINSHIP',
   'NSE:COFORGE',
   'NSE:COLPAL',
   'NSE:CONCOR',
   'NSE:COROMANDEL',
   'NSE:CREDITACC',
   'NSE:CROMPTON',
   'NSE:CUB',
   'NSE:CUMMINSIND',
   'NSE:CYIENT',
   'NSE:DABUR',
   'NSE:DALBHARAT',
   'NSE:DATAPATTNS',
   'NSE:DCBBANK',
   'NSE:DCMSHRIRAM',
   'NSE:DEEPAKNTR',
   'NSE:DELHIVERY',
   'NSE:DEVYANI',
   'NSE:DHAMPURSUG',
   'NSE:DIVISLAB',
   'NSE:DIXON',
   'NSE:DLF',
   'NSE:DMART',
   'NSE:DRREDDY',
   'NSE:EICHERMOT',
   'NSE:EIDPARRY',
   'NSE:EIHOTEL',
   'NSE:ELGIEQUIP',
   'NSE:EMAMILTD',
   'NSE:ENGINERSIN',
   'NSE:ERIS',
   'NSE:ESCORTS',
   'NSE:EXIDEIND',
   'NSE:FACT',
   'NSE:FDC',
   'NSE:FEDERALBNK',
   'NSE:FINCABLES',
   'NSE:FINEORG',
   'NSE:FIRSTCRY',
   'NSE:FIVESTAR',
   'NSE:FORTIS',
   'NSE:GAIL',
   'NSE:GALAXYSURF',
   'NSE:GATI',
   'NSE:GICRE',
   'NSE:GILLETTE',
   'NSE:GLAXO',
   'NSE:GLENMARK',
   'NSE:GMDCLTD',
   'NSE:GMRAIRPORT',
   'NSE:GNFC',
   'NSE:GODAWARI',
   'NSE:GODREJCP',
   'NSE:GODREJPROP',
   'NSE:GOKEX',
   'NSE:GPPL',
   'NSE:GRANULES',
   'NSE:GRAPHITE',
   'NSE:GRASIM',
   'NSE:GRAVITA',
   'NSE:GREENPANEL',
   'NSE:GREENPLY',
   'NSE:GRINDWELL',
   'NSE:GRINFRA',
   'NSE:GRSE',
   'NSE:GSFC',
   'NSE:GSPL',
   'NSE:GUJALKALI',
   'NSE:GUJGASLTD',
   'NSE:HAL',
   'NSE:HAPPSTMNDS',
   'NSE:HATSUN',
   'NSE:HAVELLS',
   'NSE:HBLENGINE',
   'NSE:HCLTECH',
   'NSE:HDFCAMC',
   'NSE:HDFCBANK',
   'NSE:HDFCLIFE',
   'NSE:HEG',
   'NSE:HERITGFOOD',
   'NSE:HEROMOTOCO',
   'NSE:HFCL',
   'NSE:HGINFRA',
   'NSE:HINDALCO',
   'NSE:HINDCOPPER',
   'NSE:HINDPETRO',
   'NSE:HINDUNILVR',
   'NSE:HINDZINC',
   'NSE:HONAUT',
   'NSE:HUDCO',
   'NSE:HYUNDAI',
   'NSE:ICICIBANK',
   'NSE:ICICIGI',
   'NSE:ICICIPRULI',
   'NSE:IDEA',
   'NSE:IDFC',
   'NSE:IDFCFIRSTB',
   'NSE:IEX',
   'NSE:IGL',
   'NSE:IIFL',
   'NSE:INDHOTEL',
   'NSE:INDIAMART',
   'NSE:INDIANB',
   'NSE:INDIGO',
   'NSE:INDOCO',
   'NSE:INDUSINDBK',
   'NSE:INDUSTOWER',
   'NSE:INFY',
   'NSE:INOXINDIA',
   'NSE:INOXWIND',
   'NSE:INTELLECT',
   'NSE:IOB',
   'NSE:IOC',
   'NSE:IPCALAB',
   'NSE:IRB',
   'NSE:IRCON',
   'NSE:IRCTC',
   'NSE:IRFC',
   'NSE:ISGEC',
   'NSE:ITC',
   'NSE:ITCHOTELS',
   'NSE:ITI',
   'NSE:J&KBANK',
   'NSE:JBCHEPHARM',
   'NSE:JINDALSAW',
   'NSE:JINDALSTEL',
   'NSE:JIOFIN',
   'NSE:JKCEMENT',
   'NSE:JKPAPER',
   'NSE:JSL',
   'NSE:JSWENERGY',
   'NSE:JSWINFRA',
   'NSE:JSWSTEEL',
   'NSE:JUBLFOOD',
   'NSE:JUBLINGREA',
   'NSE:JUBLPHARMA',
   'NSE:JUSTDIAL',
   'NSE:JWL',
   'NSE:JYOTHYLAB',
   'NSE:JYOTICNC',
   'NSE:KAJARIACER',
   'NSE:KALYANKJIL',
   'NSE:KANSAINER',
   'NSE:KARURVYSYA',
   'NSE:KAYNES',
   'NSE:KEI',
   'NSE:KFINTECH',
   'NSE:KIMS',
   'NSE:KIRLOSBROS',
   'NSE:KIRLOSENG',
   'NSE:KNRCON',
   'NSE:KOLTEPATIL',
   'NSE:KOTAKBANK',
   'NSE:KPIGREEN',
   'NSE:KPITTECH',
   'NSE:KPRMILL',
   'NSE:KRBL',
   'NSE:LALPATHLAB',
   'NSE:LATENTVIEW',
   'NSE:LAURUSLABS',
   'NSE:LEMONTREE',
   'NSE:LICHSGFIN',
   'NSE:LICI',
   'NSE:LINDEINDIA',
   'NSE:LLOYDSME',
   'NSE:LODHA',
   'NSE:LT',
   'NSE:LTF',
   'NSE:LTIM',
   'NSE:LUPIN',
   'NSE:M&M',
   'NSE:M&MFIN',
   'NSE:MAHABANK',
   'NSE:MAHLIFE',
   'NSE:MAHLOG',
   'NSE:MAHSEAMLES',
   'NSE:MANAPPURAM',
   'NSE:MANKIND',
   'NSE:MAPMYINDIA',
   'NSE:MARICO',
   'NSE:MARKSANS',
   'NSE:MARUTI',
   'NSE:MASTEK',
   'NSE:MAXHEALTH',
   'NSE:MAZDOCK',
   'NSE:MCX',
   'NSE:MEDANTA',
   'NSE:METROPOLIS',
   'NSE:MGL',
   'NSE:MOBIKWIK',
   'NSE:MOIL',
   'NSE:MOREPENLAB',
   'NSE:MOTHERSON',
   'NSE:MOTILALOFS',
   'NSE:MPHASIS',
   'NSE:MRF',
   'NSE:MUTHOOTFIN',
   'NSE:NAM-INDIA',
   'NSE:NATCOPHARM',
   'NSE:NATIONALUM',
   'NSE:NAUKRI',
   'NSE:NAVINFLUOR',
   'NSE:NBCC',
   'NSE:NCC',
   'NSE:NESTLEIND',
   'NSE:NETWEB',
   'NSE:NEULANDLAB',
   'NSE:NEWGEN',
   'NSE:NH',
   'NSE:NHPC',
   'NSE:NIACL',
   'NSE:NIVABUPA',
   'NSE:NMDC',
   'NSE:NTPC',
   'NSE:NTPCGREEN',
   'NSE:NUVAMA',
   'NSE:NYKAA',
   'NSE:OBEROIRLTY',
   'NSE:OFSS',
   'NSE:OIL',
   'NSE:OLAELEC',
   'NSE:ONGC',
   'NSE:ORCHPHARMA',
   'NSE:PAGEIND',
   'NSE:PARADEEP',
   'NSE:PARAS',
   'NSE:PATANJALI',
   'NSE:PAYTM',
   'NSE:PEL',
   'NSE:PERSISTENT',
   'NSE:PETRONET',
   'NSE:PFC',
   'NSE:PFIZER',
   'NSE:PGHH',
   'NSE:PHOENIXLTD',
   'NSE:PIDILITIND',
   'NSE:PIIND',
   'NSE:PNB',
   'NSE:PNCINFRA',
   'NSE:POLICYBZR',
   'NSE:POLYCAB',
   'NSE:POONAWALLA',
   'NSE:POWERGRID',
   'NSE:PPLPHARMA',
   'NSE:PRAJIND',
   'NSE:PREMIERENE',
   'NSE:PRESTIGE',
   'NSE:PSB',
   'NSE:PVRINOX',
   'NSE:RADICO',
   'NSE:RAILTEL',
   'NSE:RAINBOW',
   'NSE:RALLIS',
   'NSE:RAMCOCEM',
   'NSE:RATEGAIN',
   'NSE:RATNAMANI',
   'NSE:RAYMOND',
   'NSE:RBLBANK',
   'NSE:RCF',
   'NSE:RECLTD',
   'NSE:RELAXO',
   'NSE:RELIANCE',
   'NSE:RITES',
   'NSE:ROUTE',
   'NSE:RRKABEL',
   'NSE:RVNL',
   'NSE:SAIL',
   'NSE:SANDUMA',
   'NSE:SANOFI',
   'NSE:SAPPHIRE',
   'NSE:SBICARD',
   'NSE:SBILIFE',
   'NSE:SBIN',
   'NSE:SCHAEFFLER',
   'NSE:SCI',
   'NSE:SENCO',
   'NSE:SEQUENT',
   'NSE:SHARDACROP',
   'NSE:SHILPAMED',
   'NSE:SHOPERSTOP',
   'NSE:SHREECEM',
   'NSE:SHRIRAMFIN',
   'NSE:SHYAMMETL',
   'NSE:SIEMENS',
   'NSE:SIGNATURE',
   'NSE:SJVN',
   'NSE:SKFINDIA',
   'NSE:SOBHA',
   'NSE:SOLARA',
   'NSE:SOLARINDS',
   'NSE:SONATSOFTW',
   'NSE:SOUTHBANK',
   'NSE:SPICEJET',
   'NSE:SRF',
   'NSE:STAR',
   'NSE:STARHEALTH',
   'NSE:STLTECH',
   'NSE:SUMICHEM',
   'NSE:SUNDARMFIN',
   'NSE:SUNPHARMA',
   'NSE:SUNTECK',
   'NSE:SUNTV',
   'NSE:SUPREMEIND',
   'NSE:SUVENPHAR',
   'NSE:SUZLON',
   'NSE:SWIGGY',
   'NSE:SYMPHONY',
   'NSE:SYNGENE',
   'NSE:SYRMA',
   'NSE:TANLA',
   'NSE:TATACHEM',
   'NSE:TATACOFFEE',
   'NSE:TATACOMM',
   'NSE:TATACONSUM',
   'NSE:TATAELXSI',
   'NSE:TATAINVEST',
   'NSE:TATAMOTORS',
   'NSE:TATAPOWER',
   'NSE:TATASTEEL',
   'NSE:TATATECH',
   'NSE:TCIEXP',
   'NSE:TCS',
   'NSE:TECHM',
   'NSE:TEJASNET',
   'NSE:TEXRAIL',
   'NSE:THANGAMAYL',
   'NSE:THERMAX',
   'NSE:THYROCARE',
   'NSE:TIINDIA',
   'NSE:TIMKEN',
   'NSE:TITAGARH',
   'NSE:TITAN',
   'NSE:TORNTPHARM',
   'NSE:TORNTPOWER',
   'NSE:TRANSFORMER',
   'NSE:TRENT',
   'NSE:TRIDENT',
   'NSE:TRITURBINE',
   'NSE:TRIVENI',
   'NSE:TTKPRESTIG',
   'NSE:TVSMOTOR',
   'NSE:UBL',
   'NSE:UCOBANK',
   'NSE:ULTRACEMCO',
   'NSE:UNICHEMLAB',
   'NSE:UNIONBANK',
   'NSE:UNITDSPR',
   'NSE:UPL',
   'NSE:UTIAMC',
   'NSE:VBL',
   'NSE:VEDL',
   'NSE:VENUSREM',
   'NSE:VGUARD',
   'NSE:VINATIORGA',
   'NSE:VIPIND',
   'NSE:VMART',
   'NSE:VOLTAMP',
   'NSE:VOLTAS',
   'NSE:VTL',
   'NSE:WAAREEENER',
   'NSE:WELCORP',
   'NSE:WELSPUNLIV',
   'NSE:WESTLIFE',
   'NSE:WHIRLPOOL',
   'NSE:WIPRO',
   'NSE:WOCKPHARMA',
   'NSE:WSTCSTPAPR',
   'NSE:YESBANK',
   'NSE:ZENSARTECH',
   'NSE:ZENTEC',
   'NSE:ZOMATO',
   'NSE:ZYDUSLIFE'
 );

commit;

-- Verify: expect forex 78, indian 476.
select trading_mode, count(*) filter (where is_active) as active from public.instruments group by trading_mode;

-- Spot-check the specs that were wrong before:
select symbol, contract_size, pip_size from public.instruments
where symbol in ('XAU/USD', 'XAG/USD', 'EUR/USD', 'USD/JPY') order by symbol;
